/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ContentAuthenticityRegistry {
  export type VerificationRecordStruct = {
    contentHash: BytesLike;
    ipfsCid: string;
    verifier: AddressLike;
    timestamp: BigNumberish;
    isAuthentic: boolean;
    confidenceScore: BigNumberish;
    detectionType: BigNumberish;
    exists: boolean;
  };

  export type VerificationRecordStructOutput = [
    contentHash: string,
    ipfsCid: string,
    verifier: string,
    timestamp: bigint,
    isAuthentic: boolean,
    confidenceScore: bigint,
    detectionType: bigint,
    exists: boolean
  ] & {
    contentHash: string;
    ipfsCid: string;
    verifier: string;
    timestamp: bigint;
    isAuthentic: boolean;
    confidenceScore: bigint;
    detectionType: bigint;
    exists: boolean;
  };
}

export interface ContentAuthenticityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchRegisterVerifications"
      | "generateContentHash"
      | "getPaginatedVerifications"
      | "getUserVerificationCount"
      | "getUserVerifications"
      | "getVerification"
      | "isVerified"
      | "owner"
      | "pause"
      | "paused"
      | "registerVerification"
      | "renounceOwnership"
      | "setVerificationFee"
      | "totalVerifications"
      | "transferOwnership"
      | "unpause"
      | "updateVerificationCid"
      | "verificationFee"
      | "verifications"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContentVerified"
      | "FeeUpdated"
      | "FundsWithdrawn"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
      | "VerificationUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchRegisterVerifications",
    values: [BytesLike[], string[], boolean[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "generateContentHash",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaginatedVerifications",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVerificationCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVerifications",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerification",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerVerification",
    values: [BytesLike, string, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setVerificationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVerifications",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateVerificationCid",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifications",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "batchRegisterVerifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateContentHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaginatedVerifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVerificationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVerifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerificationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVerifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateVerificationCid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace ContentVerifiedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    ipfsCid: string,
    verifier: AddressLike,
    isAuthentic: boolean,
    confidenceScore: BigNumberish,
    detectionType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    ipfsCid: string,
    verifier: string,
    isAuthentic: boolean,
    confidenceScore: bigint,
    detectionType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    ipfsCid: string;
    verifier: string;
    isAuthentic: boolean;
    confidenceScore: bigint;
    detectionType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationUpdatedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    newIpfsCid: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    newIpfsCid: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    newIpfsCid: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ContentAuthenticityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ContentAuthenticityRegistry;
  waitForDeployment(): Promise<this>;

  interface: ContentAuthenticityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchRegisterVerifications: TypedContractMethod<
    [
      _contentHashes: BytesLike[],
      _ipfsCids: string[],
      _isAuthentic: boolean[],
      _confidenceScores: BigNumberish[],
      _detectionTypes: BigNumberish[]
    ],
    [void],
    "payable"
  >;

  generateContentHash: TypedContractMethod<
    [_content: string],
    [string],
    "view"
  >;

  getPaginatedVerifications: TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [string[]],
    "view"
  >;

  getUserVerificationCount: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  getUserVerifications: TypedContractMethod<
    [_user: AddressLike],
    [string[]],
    "view"
  >;

  getVerification: TypedContractMethod<
    [_contentHash: BytesLike],
    [ContentAuthenticityRegistry.VerificationRecordStructOutput],
    "view"
  >;

  isVerified: TypedContractMethod<[_contentHash: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerVerification: TypedContractMethod<
    [
      _contentHash: BytesLike,
      _ipfsCid: string,
      _isAuthentic: boolean,
      _confidenceScore: BigNumberish,
      _detectionType: BigNumberish
    ],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setVerificationFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalVerifications: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateVerificationCid: TypedContractMethod<
    [_contentHash: BytesLike, _newIpfsCid: string],
    [void],
    "nonpayable"
  >;

  verificationFee: TypedContractMethod<[], [bigint], "view">;

  verifications: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean, bigint, bigint, boolean] & {
        contentHash: string;
        ipfsCid: string;
        verifier: string;
        timestamp: bigint;
        isAuthentic: boolean;
        confidenceScore: bigint;
        detectionType: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchRegisterVerifications"
  ): TypedContractMethod<
    [
      _contentHashes: BytesLike[],
      _ipfsCids: string[],
      _isAuthentic: boolean[],
      _confidenceScores: BigNumberish[],
      _detectionTypes: BigNumberish[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "generateContentHash"
  ): TypedContractMethod<[_content: string], [string], "view">;
  getFunction(
    nameOrSignature: "getPaginatedVerifications"
  ): TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserVerificationCount"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserVerifications"
  ): TypedContractMethod<[_user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVerification"
  ): TypedContractMethod<
    [_contentHash: BytesLike],
    [ContentAuthenticityRegistry.VerificationRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[_contentHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerVerification"
  ): TypedContractMethod<
    [
      _contentHash: BytesLike,
      _ipfsCid: string,
      _isAuthentic: boolean,
      _confidenceScore: BigNumberish,
      _detectionType: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerificationFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalVerifications"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateVerificationCid"
  ): TypedContractMethod<
    [_contentHash: BytesLike, _newIpfsCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verificationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifications"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean, bigint, bigint, boolean] & {
        contentHash: string;
        ipfsCid: string;
        verifier: string;
        timestamp: bigint;
        isAuthentic: boolean;
        confidenceScore: bigint;
        detectionType: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ContentVerified"
  ): TypedContractEvent<
    ContentVerifiedEvent.InputTuple,
    ContentVerifiedEvent.OutputTuple,
    ContentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationUpdated"
  ): TypedContractEvent<
    VerificationUpdatedEvent.InputTuple,
    VerificationUpdatedEvent.OutputTuple,
    VerificationUpdatedEvent.OutputObject
  >;

  filters: {
    "ContentVerified(bytes32,string,address,bool,uint8,uint8,uint256)": TypedContractEvent<
      ContentVerifiedEvent.InputTuple,
      ContentVerifiedEvent.OutputTuple,
      ContentVerifiedEvent.OutputObject
    >;
    ContentVerified: TypedContractEvent<
      ContentVerifiedEvent.InputTuple,
      ContentVerifiedEvent.OutputTuple,
      ContentVerifiedEvent.OutputObject
    >;

    "FeeUpdated(uint256,uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "FundsWithdrawn(address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VerificationUpdated(bytes32,string,uint256)": TypedContractEvent<
      VerificationUpdatedEvent.InputTuple,
      VerificationUpdatedEvent.OutputTuple,
      VerificationUpdatedEvent.OutputObject
    >;
    VerificationUpdated: TypedContractEvent<
      VerificationUpdatedEvent.InputTuple,
      VerificationUpdatedEvent.OutputTuple,
      VerificationUpdatedEvent.OutputObject
    >;
  };
}
