networks:
  web_net:
    external: true

services:
  askmira:
    image: docker.cache.whaleintel.me/askmira-front:latest
    container_name: askmira-front
    restart: on-failure
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      - "traefik.http.routers.ai-askmira.entrypoints=http"
      - "traefik.http.routers.ai-askmira.rule=Host(`${traefik_host_rule}`)"
      - "traefik.http.routers.ai-askmira.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.askmira-auth.basicauth.users=${WEB_AUTH_USER}:${WEB_AUTH_PASS}"
      # - "traefik.http.routers.ai-askmira-secure.middlewares=askmira-auth"
      - "traefik.http.routers.ai-askmira-secure.entrypoints=https"
      - "traefik.http.routers.ai-askmira-secure.rule=Host(`${traefik_host_rule}`)"
      - "traefik.http.routers.ai-askmira-secure.tls=true"
      - "traefik.http.routers.ai-askmira-secure.tls.options=default"
      - "traefik.http.routers.ai-askmira-secure.tls.certresolver=mycert"
      - "traefik.http.services.ai-askmira.loadbalancer.server.port=5000"
    networks:
      - web_net

